# netlify.toml
[[redirects]]
from = "/projects/blog/:id"
to = "/projects/blog/[id].html"
status = 200
force = false

[build]
  publish = ""
  command = "yarn build"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"